### ISSUE TITLE
Repackage video files on the fly to support streaming to <video> tag

### ISSUE THREAD

**Issue by achernar** [feross/instant.io#10]
i cannot stream any video
i always receive this error...

Uncaught InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source. bundle.js:10746

**Comment by feross** [comment]
Thanks for the recommendation. mp4box.js looks like a good start. I wish it used browserify and streams.

**Comment by feross** [comment]
An initial implementation of on-the-fly video repackaging has been live on https://instant.io for a couple months, thanks to @jhiesey and mp4box.js. It still needs some work to make it more robust, but this issue is complete now.
