### ISSUE TITLE
cors header for instant.rom1504.fr

### ISSUE THREAD

**Issue by rom1504** [feross/instant.io#102]
> 14:34 rom1504> feross: I'm getting "XMLHttpRequest cannot load https://instant.io/rtcConfig. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin  'https://instant.rom1504.fr' is therefore not allowed access." on instant.rom1504.fr, not sure if that's normal
> 17:57 feross> rom1504: can you open an issue for that and I'll add the right header for your https domain :)

Thanks !

**Comment by feross** [comment]
This is fixed now :)
