### ISSUE TITLE
it's nothing do action 

### ISSUE THREAD

**Issue by asifagaria** [feross/instant.io#105]
i run it wan a upload image or any file nothing to do anything

![image](https://cloud.githubusercontent.com/assets/19821/14067864/e269f3ba-f488-11e5-9f85-131860d13ebf.png)

**Comment by asifagaria** [comment]
showing error 

![image](https://cloud.githubusercontent.com/assets/19821/14068030/ea5691da-f48f-11e5-9ecd-7bce44957c7b.png)

**Comment by feross** [comment]
Looks like you're missing an npm dependency. Try deleting your `node_modules` folder and re-running `npm install`.

**Comment by asifagaria** [comment]
Dear Sir How To Change tracker links announce like this 

udp://exodus.desync.com:6969

udp://tracker.coppersurfer.tk:6969

udp://tracker.internetwarriors.net:1337

udp://tracker.leechers-paradise.org:6969
