### ISSUE TITLE
Add own turn server

### ISSUE THREAD

**Issue by iouss** [feross/instant.io#111]
Hello,

Please, could you help me to set my own turn server ?

thanks 

Oussama

**Comment by feross** [comment]
Sorry -- this is not a support forum.

I use [this Twilio service](https://www.twilio.com/stun-turn) for TURN.

**Comment by iouss** [comment]
Hello,

Thanks for your help, I'll try to put a static Turn server.

Regards,
Oussama


On Thu, Jun 2, 2016 at 10:20 PM, Feross Aboukhadijeh <
notifications@github.com> wrote:

> Sorry -- this is not a support forum.
>
> I use this Twilio service <https://www.twilio.com/stun-turn> for TURN.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/feross/instant.io/issues/111#issuecomment-223409933>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFSHTVXT-z7-azh24XpPKaEgm4DKdAnLks5qHzsbgaJpZM4IslNX>
> .
>



-- 
Avec mes cordiales salutations.
*Oussama GHERMOUL *
06 68 43 17 56
