### ISSUE TITLE
Error at start: /usr/bin/env: node: No such file or directory

### ISSUE THREAD

**Issue by kanzakignt** [feross/instant.io#112]
Hello,  @feross (feross)

This might sound like a stupid question but I'm having a hard time installing an instant.io clone for a zeronet website.

I get the following error code after "npm start"

```
/usr/bin/env: node: No such file or directory
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```

Any idea on what could fix it?

Thanks!

**Comment by joshterrill** [comment]
How did you install node? The error says that it might be to the use of using `legacy-node`. Is that what you have?

**Comment by feross** [comment]
On Debian-based systems you need to install `nodejs-legacy` which installs a symlink from `node` to `nodejs`.

```
sudo apt-get install nodejs-legacy
```

To get Instant.io working over ZeroNet, though, you probably don't want to use Node.js at all. You can actually make a version of Instant.io that has no server-side component at all. The server here is just to serve the basic HTML and expose the (optional) TURN credentials.
