### ISSUE TITLE
File length too large for Blob URL approach

### ISSUE THREAD

**Issue by sweety808** [feross/instant.io#118]
Giving the possibility to stream big files

Error rendering file "filename": File length too large for Blob URL approach: 1800619884 (max: 200000000)

**Comment by feross** [comment]
Fixed.

**Comment by alex2844** [comment]
![screenshot 2018-12-04 at 20 15 06](https://user-images.githubusercontent.com/18526177/49451670-84b65e00-f801-11e8-90f1-d4fb4583754f.png)

**Comment by chisNaN** [comment]
Lol same for me just now i am using `webtorrent@latest`

**Comment by ofirkris** [comment]
Same issue here

**Comment by feross** [comment]
This limit is not about limiting the max file size that we can stream. This is about what to do when the streaming approach fails and we are forced to use the Blob fallback approach. We keep it set to 2GB for now since the full file has to be loaded into memory and we don't want to crash the browser tab.

**Comment by PaTiToMaSteR** [comment]
Still failing for me in the latest version. Can you elaborate more the answer @feross ?

> error: Error: Error rendering file "Sample 4k 60P UHD (Ultra HD) video download of Rio (2160p_60fps_VP9-128kbit_AAC).mkv": File length too large for Blob URL approach: 451618597 (max: 200000000)

Any solution? Good practice? My file is 440MB
Sample 4k 60P UHD (Ultra HD) video download of Rio (2160p_60fps_VP9-128kbit_AAC).mkv

**Comment by PaTiToMaSteR** [comment]
In the documentation says: 
For video and audio, webtorrent tries multiple methods of playing the file:

videostream -- best option, supports streaming with seeking, but only works with MP4-based files for now (uses MediaSource API)
mediasource -- supports more formats, supports streaming without seeking (uses MediaSource API)
Blob URL -- supports the most formats of all (anything the <video> tag supports from an http url), with seeking, but does not support streaming (entire file must be downloaded first)

Then that means for now, we cannot use mkv for big files, Am I right?
