### ISSUE TITLE
Uncaught TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by goldenratio** [feross/instant.io#120]
It doesn't work.
Demo URL https://instant.io/#9c98134a9702aadfb90394ae8ab21cd5436578a6

Chrome console log
```
bundle.js:17453 Uncaught TypeError: Cannot read property 'slice' of undefined
bundle.js:17499 Uncaught TypeError: Cannot read property 'sync' of undefined
bundle.js:17453 Uncaught TypeError: Cannot read property 'slice' of undefined
```

Firefox console log 
```
Successfully compiled asm.js code (total compilation time 3ms; not stored in cache (too small to benefit))bundle.js
TypeError: track.inStream is undefined
[122]</</MP4Remuxer.prototype.seek/</writeFragment/<()
bundle.js:17453
[69]</Item.prototype.run()
bundle.js:9540
drainQueue()
bundle.js:9510
bundle.js:17453:9

```

Video file format was mp4

Update:
If I use .gif format it works 
https://instant.io/#c908b6306955a46577f5a4780b982fa1a466c371

**Comment by feross** [comment]
Wow, this is an interesting bug. Can you email me the .mp4 file you were using so I can investigate this further? My email is on my github profile page.

Thanks!

**Comment by goldenratio** [comment]
sent.

**Comment by jhiesey** [comment]
I'll take a look as soon as I can, which probably means this weekend or so.

**Comment by feross** [comment]
Thanks, @jhiesey!
