### ISSUE TITLE
SSL Cert: Hostname mismatch 

### ISSUE THREAD

**Issue by tmikaeld** [feross/instant.io#121]
![screenshot_2016-09-16_10-02-44_am](https://cloud.githubusercontent.com/assets/907195/18579239/c1cddb1e-7bf4-11e6-9ebf-f5191422b6ea.png)

**Comment by tmikaeld** [comment]
Seems you applied webtorrent.io to instant.io

**Comment by timfish** [comment]
and due to HSTS being enabled, I cant ignore the error!

**Comment by roccomuso** [comment]
+1

**Comment by feross** [comment]
Sorry folks -- I'm looking into this now.

I recently migrated the server from my personal account to a WebTorrent dedicated hosting account and it looks like it wasn't perfectly smooth.

Will update here.

**Comment by tmikaeld** [comment]
@feross 

Please don't stress about it, It's a free service and we are all grateful. 
I just wanted to make sure it doesn't go unnoticed for too long ;-)

**Comment by feross** [comment]
@tmikaeld Thanks 👍

**Comment by feross** [comment]
Turns out this was a simple DNS misconfiguration. When moving the DNS over, I pasted the IP of webtorrent.io for instant.io. 😵 

It's fixed now, but it could take a few hours for DNS to propagate across the internet.

Cheers! 🎉

**Comment by tmikaeld** [comment]
@feross 

Thanks for fixing it so fast! Skål!* 

(*Cheers in Swedish)

**Comment by feross** [comment]
Nice, I know this greeting from my Danish friend where the greeting is the same.

Skål!
