### ISSUE TITLE
Show download estimated time of arrival

### ISSUE THREAD

**Issue by Eido95** [feross/instant.io#122]
First of all, this is an amazing project! I've just used it with my smartphone.

Second of all, I suggest you to show user-friendly ETA text.
I've searched in the docs of both webtorrent and webrtc for any ETA text output, but didn't find anything, so it seems like it should be calculated on the fly.

**Comment by toXel** [comment]
I'd like to work on this!

**Comment by feross** [comment]
@toXel Go for it! We show an estimated time on https://webtorrent.io. You can just re-use that code from here: https://github.com/feross/webtorrent-www/blob/4c0bc5282003a8c157104e0ca7e45f9c4dd7a39c/client/views/home.js#L111-L118

**Comment by toXel** [comment]
Should I also use moment.js to get a humanized time? Or is something like `1m 34s` better?

**Comment by toXel** [comment]
I did it with moment.js now. Looks like this:
![image](https://cloud.githubusercontent.com/assets/2300709/19495076/227faa40-9582-11e6-9f16-1f227301f25f.png)

If it's okay I would create a PR

**Comment by toXel** [comment]
I've just checked how the ETA is displayed in WebTorrent Desktop. Maybe that would be a more appropriate way for instant.io than the one on the WebTorrent page?

It's here: https://github.com/feross/webtorrent-desktop/blob/master/src/renderer/pages/torrent-list-page.js#L185-L204
