### ISSUE TITLE
Instant.io doesn't play

### ISSUE THREAD

**Issue by phr34k0** [feross/instant.io#124]
Copied tons of magnets and tons of seeds from 1337x.to and it doesn't play. Just stuck.

![image](https://cloud.githubusercontent.com/assets/13272249/18847149/b4c42512-845b-11e6-8c32-eb96529af1a8.png)

**Comment by uriva** [comment]
+1 it seems the default trackers stopped working

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. We cannot assist you.
