### ISSUE TITLE
unsupported file type ".zip": cannot append to DOM

### ISSUE THREAD

**Issue by thadguidry** [feross/instant.io#130]
On Windows 10 64bit, I tried to copy paste the Apache NiFi zip file for latest version to instant.io
and received the error:

```
Peers: 0 Progress: 100.0% Download speed: 0 B/s Upload speed: 0 B/s
Seeding 1 files
"nifi-1.1.0-bin.torrent" contains 1 files:
  - nifi-1.1.0-bin.zip (761 MB)
Torrent info hash: d5a233e8967a805be01d9f5561a11c29ccb76bb7 [Share link] [Magnet URI] [Download .torrent]
Unsupported file type ".zip": Cannot append to DOM
Download nifi-1.1.0-bin.zip
```

**Comment by feross** [comment]
That's an expected message, since .zip files can't be rendered to the DOM. UX could be better, but instant.io is currently mostly used as a tech demo.

I plan to improve the UX one day so messages like this won't appear.
