### ISSUE TITLE
Failed to start download from bittornado tracker

### ISSUE THREAD

**Issue by Quix0r** [feross/instant.io#133]
I run a personal (all only free-libre software or data, e.g. FlightGear) tracker at http://mxchange.org:23456/ I have downloaded one torrent from there and tried it on instant.io, but no download starts.

I will retest the same torrent at home, normally it should start there.

**Comment by feross** [comment]
@Quix0r There needs to be at least one seeder that can talk to "web peers" over WebRTC for your torrent to work on https://instant.io. There is more info about this in the FAQ: https://webtorrent.io/faq

**Comment by Quix0r** [comment]
Okay, so the bittornado.many needs to support WebRTC.

**Comment by feross** [comment]
You don't need to get any specific tracker to support WebRTC. You just need to ensure that a WebTorrent compatible client like [WebTorrent Desktop](https://webtorrent.io/desktop/) is seeding the torrent.

**Comment by Quix0r** [comment]
Well, still not working, even with a "port-less" URL:

1. Download https://tracker.mxchange.org/file?info_hash=%BC%0A%85Bv%E7%10%CF%10_%01%12%3F%A7U%E5%A9b%CF%A3
2. Open https://instant.io/
3. Choose the just downloaded torrent. There is one peer listening on default ports (51413 to 51415)

**Comment by Quix0r** [comment]
Also this is not working, but should work:
https://instant.io/#magnet%3A%3Fxt%3Durn%3Abtih%3Abc0a854276e710cf105f01123fa755e5a962cfa3%26dn%3Dfgdata_new-update-001.bundle%26tr%3Dhttps%253A%252F%252Ftracker.mxchange.org%252Fannounce
