### ISSUE TITLE
Ability to set torrent file name

### ISSUE THREAD

**Issue by alethiophile** [feross/instant.io#135]
As it stands, if you select multiple files the resultant torrent is just named after the first one. It would be nice to be able to set the name in this case.

**Comment by feross** [comment]
If you want to create your own torrent and set all the options, I suggest using [`create-torrent`](https://github.com/feross/create-torrent), which has a command line program will let you set the name. Unfortunately, I don't think we want to complicate the instant.io UI with a name form.
