### ISSUE TITLE
Mirrors are down

### ISSUE THREAD

**Issue by DiegoRBaquero** [feross/instant.io#137]
Both mirrors are down.

**Comment by feross** [comment]
Hey, @rom1504 @ghost, looks like your Instant.io mirrors are down. Want to take a look?

**Comment by desci** [comment]
I have another mirror that I am setting up, but the part of configuring WebRTC is not documented, so I'm actually starting to figure out what a WebRTC is. If someone could give me pointers, I'd do it faster.

This is my instance's log:

> `Could not get WebRTC config from server. Using default (without TURN).`

**Comment by rom1504** [comment]
I got my mirror up again, but I'm getting errors now.
`WebSocket connection to 'wss://tracker.webtorrent.io/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED`

**Comment by DiegoRBaquero** [comment]
@desci It's because it's trying to obtain the rtcConfig hosted in instant.io but it doesn't have permission.

@rom1504 webtorrent tracker has been down for some months now.

**Comment by rom1504** [comment]
@DiegoRBaquero How can instant.io work without the webtorrent tracker ?

**Comment by DiegoRBaquero** [comment]
With BTorrent, FastCast and OpenWebTorrent trackers.

**Comment by feross** [comment]
@desci That warning can be safely ignored. If you want to eliminate it, sign up for a Twilio account and set up Network Traversal, i.e. TURN https://www.twilio.com/stun-turn and paste your credentials into a file called `secret/index.js`. You can see a sample of what it should look like here: https://github.com/feross/instant.io/blob/master/secret/index-sample.js

A TURN server will be used if a direct P2P connection can't be established between two peers, but it's centralized so you have to run it (and pay for it, though it should be cheap if you don't have thousands of visitors).
