### ISSUE TITLE
thanks for the work

### ISSUE THREAD

**Issue by PramUkesh** [feross/instant.io#139]
i dont know where i have to start talking because you are the mirror programmer to me 
i always play with torrents upto now i downloaded a 5000 torrent files till now each have 1 GB file space 
when downloading those files i always want to as software developer as beginer want to integrate the browser what ever it may android browser and the site in a single program but i dont try that means then i want to build the client side program that can compile the torrent file and download it including the features like stearming the audio or video as the case may be but you came up with a best server side script with revolutionary change in the torrent life you may not believe even though i was familiar with some programming languages and used lots of open source github source codes but till now i do not have a git hub account i opened this github account by just watching your video about torrenting thanks for open sourcing the project because when there is a revolutionary in some area of information technology it should be open sourced which can be usable to others so as  a last word i will try to put maximum effort to contribute to your project because it is my as dream to integrate the browser with such a torrent technology.
                                                                                                                                          -Thanks FeROsS

**Comment by feross** [comment]
Hi @PramUkesh, thanks for your kind words. If you get a chance to contribute, that would be great. Cheers!
