### ISSUE TITLE
Error in /instant.io-master/server/index.js

### ISSUE THREAD

**Issue by kyonetca** [feross/instant.io#20]
Hello,
just leaving a bugfix that there is an issue with code located here

app.use(express.static(path.join(__dirname, '../static')))

my editor does not seem to like express.static 

(static comes up as red)

Let me know if anyone figured it out or if it is just my coder.

Cheers
K!

**Comment by feross** [comment]
This is not an issue. Your editor probably thinks `static` is a keyword, but it's okay to use static as a property name in JavaScript.
