### ISSUE TITLE
Trigger.sh is asking for password

### ISSUE THREAD

**Issue by raptats** [feross/instant.io#21]
Hi Ferros,

I have removed the node modules of the clone so that i can install the "bin" files but for some reason it asks for a password. Is it required for me to implement these .sh files or should I continue with browserifying the indexes? Thanks for your help in advance.

**Comment by feross** [comment]
The files in `bin/` are for deploying to instant.io. If you're just trying to get the site running locally on your computer, you don't need to run them.

Just run `npm install` then `npm run watch`, and visit http://localhost:9100

**Comment by raptats** [comment]
![image](https://cloud.githubusercontent.com/assets/11029758/6555644/8cb725c4-c6a2-11e4-9c9b-f1243b339a5f.png)
![image](https://cloud.githubusercontent.com/assets/11029758/6555656/9b014a38-c6a2-11e4-87a8-9900e83b0c70.png)

Hi Feross, 

Thanks for your response. 

I have tried npm run watch and got these errors(snapshots above). The errors says to *tell the author that these fails on my system*. Am I suppose to get these errors or are there solutions I can apply to run instant.io locally? 

Cheers!

**Comment by feross** [comment]
instant.io is deployed to an ubuntu linux server and hasn't been tested on
a windows machine. Sorry – you'll have to figure out how to get it working
on your own. If the solution is simple, feel free to send a PR and I'll
merge it.

**Comment by raptats** [comment]
![image](https://cloud.githubusercontent.com/assets/11029758/6652165/c0fcf974-caa0-11e4-8b83-6b1d6bb7e129.png)

Hi Feross,

Thank you for your support.

I have tried the npm install ->> npm run watch on an ubuntu server 14.04.2 and have arrived into this error. The same happens with the window installation counterpart when manually browserifying each modules. Is there a known solution for this error or am I using an incorrect operating system?

If you do have a solution for this error, maybe we can apply the same for the windows pc and have this error prevented.

Cheers!

**Comment by feross** [comment]
You need to copy the file `secret/index-sample.js` to `secret/index.js` and fill in the config information.

**Comment by asifagaria** [comment]
any guide how to run instant.io ubuntu

**Comment by feross** [comment]
@asifagaria There are instructions here: https://github.com/feross/instant.io/blob/master/README.md#run-a-copy-of-this-site-on-your-own-server

**Comment by asifagaria** [comment]
im install it it's not work

**Comment by feross** [comment]
@asifagaria Sorry, can't help you without more information.

**Comment by asifagaria** [comment]
it's nothing do action 
![image](https://cloud.githubusercontent.com/assets/19821/14067864/e269f3ba-f488-11e5-9f85-131860d13ebf.png)
