### ISSUE TITLE
Wrong magnet uri

### ISSUE THREAD

**Issue by fpinzn** [feross/instant.io#24]
Is always generating `magnet:?tr=wss%3A%2F%2Ftracker.webtorrent.io`

**Comment by feross** [comment]
What are you doing to generate this magnet link?

**Comment by fpinzn** [comment]
Upload a text file, click on download and copy the download file that appears under log.

**Comment by feross** [comment]
Sorry, I can't reproduce this. Closing for now. Feel free to open a new issue if you're still experiencing this.
