### ISSUE TITLE
saving the downloaded file

### ISSUE THREAD

**Issue by jzjzjzj** [feross/instant.io#26]
Is there an option to save the downloaded (video) file? I could not find one after downloading mp4 file; only playback option is provided.

**Comment by feross** [comment]
Right now we don't show a download link for videos. We should probably change that.

**Comment by dominictarr** [comment]
has this regressed? I have a video (that won't play in the browser) but dont see a download button (except download torrent)

**Comment by dominictarr** [comment]
oh nevermind I see you can right click on it and save the video, once it has fully loaded.

**Comment by feross** [comment]
@dominictarr Yeah, we gotta have all the data before we can create the Blob object, which is what the link points to.

**Comment by hyperfekt** [comment]
On Firefox Nightly 59.0a1, the option to save the fully downloaded video is disabled in the context menu. The link to download beneath the video is available for the initial uploader, but not for anyone visiting the link and getting it from peers.
