### ISSUE TITLE
Better large file handling

### ISSUE THREAD

**Issue by feross** [feross/instant.io#3]
Large files fail with RangeError (in Chrome)

**Comment by feross** [comment]
Haven't seen RangeError in a while, but large downloads seem to stall part-way through (around when the tab hits 2GB ram?)

**Comment by FesterCluck** [comment]
You should check to see if you are hitting your machine's paging limit.

**Comment by feross** [comment]
For a 105MB file, the page uses 540MB of memory. By commenting out bits of the code at a time, I found this breakdown:

- 90MB just for loading instant.io in chrome (incl. my browser extensions)
- 210MB from drag-drop/buffer
- 105MB from create-torrent in `webtorrent.seed`
- 105MB from `file.getBlobURL` in `onTorrent` on instant.io

We're creating lots of buffers that don't get released, it seems. Ideally, we only need to hang onto one copy of the buffer.

**Comment by feross** [comment]
There are still some leaks, but it doesn't look like we're losing any full copies of the file anymore! Progress! There's only one copy of the file in memory.

For a 360MB file:

- 90 MB for base instant.io page
- 360 MB for file
- 160 MB for webtorrent.seed (and leaks?)

cc @jhiesey

**Comment by feross** [comment]
We're now running into a bug in Chrome where blobs can't be larger than 500MB. https://code.google.com/p/chromium/issues/detail?id=375297 This looks like it's really close to being fixed though! 

I was able to seed a 1GB file in Firefox and stream to Chrome!

**Comment by feross** [comment]
***This issue was moved to https://github.com/feross/webtorrent/issues/319.***
