### ISSUE TITLE
Seed multiple torrents at once

### ISSUE THREAD

**Issue by jakefb** [feross/instant.io#30]
It would be cool if it was possible to choose what happens when more than one file is selected or dropped in. The user should be able to choose if a torrent is created from the array of files or if a torrent is created for each file so each file has its own individual hash. I'm willing to give this an attempt and make a PR.

**Comment by feross** [comment]
I'm hesitant to make the site more complicated. How would the user select which option they want?

What's wrong with dragging one file at a time in the case where you want to create separate torrents?

**Comment by jakefb** [comment]
I see your point. What I had in mind was just a window confirm() that asks the user if they want to create one torrent with all the files. If cancel is clicked separate torrents will be created. It's probably fine how it is for now though.
