### ISSUE TITLE
Have a list of demo files

### ISSUE THREAD

**Issue by rom1504** [feross/instant.io#32]
I think it would be nice to have a list of demo files (like [this](https://instant.io/#c6642b73cf82dc52b5d538fabfdf9c8e3d9e850f)) that people can download/watch to better understand what's instant.io is about.
It could be an html page or a simple markdown page (maybe in instant.io's wiki ? idk)

**Comment by jakefb** [comment]
I would be happy to do this! I could look for music, videos, and ebooks, licensed under the creative commons. Would you want to serve the files with a http server or with webtorrent?

**Comment by rom1504** [comment]
There are a lot of public domain or creative commons licenced files there https://archive.org/details/bittorrent. Might be interesting for this issue.
@jakefb well http seeding isn't implemented yet (https://github.com/feross/webtorrent/issues/67)

**Comment by feross** [comment]
Moving to https://github.com/feross/webtorrent-www/issues/27
