### ISSUE TITLE
How to run/install this?

### ISSUE THREAD

**Issue by Fastidious** [feross/instant.io#33]
Could running/installing this on one's server instructions be added? Thanks!

**Comment by feross** [comment]
Get the code:

```
git@github.com:feross/instant.io.git
cd instant.io
npm install
```

Modify the configuration options in [`config.js`](https://github.com/feross/instant.io/blob/master/config.js) to set the IP/port you want the server to listen on.

Copy [`secret/index-sample.js`](https://github.com/feross/instant.io/blob/master/secret/index-sample.js) to `secret/index.js` and set the Twilio API key if you want a NAT traversal service (to help peers connect when behind a firewall).

That should be it!

**Comment by feross** [comment]
Also, if you just want to use the WebTorrent command line script, you can learn more at https://webtorrent.io. The client-side code that instant.io uses is here: https://github.com/feross/instant.io/blob/master/client/index.js

**Comment by feross** [comment]
Instructions added to the README.

**Comment by borekon** [comment]
> Get the code:
> 
> ```
> git@github.com:feross/instant.io.git
> cd instant.io
> npm install
> ```
> 
> Modify the configuration options in [`config.js`](https://github.com/feross/instant.io/blob/master/config.js) to set the IP/port you want the server to listen on.
> 
> Copy [`secret/index-sample.js`](https://github.com/feross/instant.io/blob/master/secret/index-sample.js) to `secret/index.js` and set the Twilio API key if you want a NAT traversal service (to help peers connect when behind a firewall).
> 
> That should be it!

There's nothing to modifiy in the file config.js
It would be great to modify the REAMDE and explain how to bind to another interface than loopback
