### ISSUE TITLE
Seeding file from server

### ISSUE THREAD

**Issue by jaybekster** [feross/instant.io#42]
How could I seed files withoud internet inside NAT?

How could I seed files from the server after client have uploaded the file. Webtorrent-hybrid and webtorrent use the same websocket adress so i have an error

**Comment by feross** [comment]
Seeding without internet is possible, but you'll need to run your own STUN server inside your NAT. It's required by WebRTC.

I'm not sure what you're asking in your second question. Can you clarify?

**Comment by jaybekster** [comment]
1. I found a config to websocket global.WEBTORRENT_ANNOUNCE = [ 'wss://tracker.webtorrent.io' ]. What is it for?
2. In steps:
User upload file and share hash to other user inside NAT.
He close the seeding although the other one is starting to download.
How can I seed the uploaded file on the server by itself when nobody of clients are seeding?

**Comment by feross** [comment]
1. That just tells WebTorrent to always use that tracker, without requiring that you pass it into every `webtorrent.download` or `webtorrent.seed` call.

2. You need to have a way to tell your server to also download the file and keep a copy there. You could just upload it to the server with an XHR request. Then your server could be a [web seed](https://github.com/feross/webtorrent/issues/67) once that feature's implemented :)

**Comment by jaybekster** [comment]
I upload the file to directory /upload. Cd to /upload and typed in console webtorrent seed <filename>. In browser i open and paste infoHas but nothing is happed.
I try to seed in console and download in browser, or seed in browser and download in console - in both they it doesn't work.

**Comment by feross** [comment]
You need to use https://github.com/feross/webtorrent-hybrid

It's almost the same command. Try `webtorrent-hybrid seed .` command

**Comment by jaybekster** [comment]
ERROR: connection error to wss://tracker.webtorrent.io?24c1e44471
ERROR: If you think this is a bug in webtorrent, report it!

**Comment by feross** [comment]
It looks like you're using an old version of webtorrent-hybrid. You can check the version with `webtorrent-hybrid -v`. It should be 0.49.1. If it's not, update with `npm install webtorrent-hybrid -g`
