### ISSUE TITLE
Add a P2P chat component

### ISSUE THREAD

**Issue by saebekassebil** [feross/instant.io#45]
Just though of this. Wouldn't it be cool if you could choose to participate in some sort of chat with all your WebTorrent peers using WebRTC? Since you're sharing content it seems that you're also sharing an interest. And that's always a good place to start a conversation!

I was thinking like an opt-in sidepanel with a chat "hosted" by the peers - like [Friends](http://moose-team.github.io/friends/)!

**Comment by feross** [comment]
This is actually a pretty neat idea. It might make sense on instant.io (not built directly into WebTorrent, of course). If someone wants to take a stab at this, it might be fun to deploy it and see how/if people use it.

**Comment by feross** [comment]
This is a cool idea, but out of scope. Closing so we can stay focused. Eye on the prize.
