### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by jakefb** [feross/instant.io#46]
![screenshot from 2015-05-26 22 27 52](https://cloud.githubusercontent.com/assets/6836282/7810492/8ca25356-03f6-11e5-812c-5107861e0f15.png)

I dragged a 600 MB mp4 file onto the page

**Comment by feross** [comment]
This is a bug in the videostream package. I opened an issue there for you: https://github.com/jhiesey/videostream/issues/5

It would help @jhiesey if he had the original file to debug with. Can you email him a link to it? john [at] hiesey [dot] com

**Comment by jakefb** [comment]
I will do that. Thanks!
