### ISSUE TITLE
Privacy & legality

### ISSUE THREAD

**Issue by Sheraff** [feross/instant.io#47]
Could we assume that this method of P2P transfer is somewhat safer than more mainstream ones?

Let me explain my scenario. My sister lives in Germany where illegally downloading licensed content is under strict surveillance. You can get fined without warning and fines are usually pretty salty. She works on a boat and gets bored after work hours without internet. Before she embarks I have files I want to send her to keep busy. Like a movie that I got legally by buying it directly from the [artist's website](https://www.louisck.net/purchase/live-at-the-comedy-store), or an ebook from [a kickstarter](https://www.kickstarter.com/projects/weiner/augie-and-the-green-knight-a-childrens-adventure-b) I supported. These are legal to share with my family, and I am not planning on distributing them. Though, from the point of view of an algorithm, it might look like I'm broadcasting licensed content.

Could sharing through instant.io be considered safe? Or will she get fined if I choose to send her files this way?

**Comment by Pawtiko** [comment]
I would reccoment using https://reep.io/ which is more private.

**Comment by feross** [comment]
This isn't something I cannot comment on. You should seek your own legal counsel. Please don't use https://instant.io for sharing copyrighted content. The WebTorrent project does not condone copyright infringement.
