### ISSUE TITLE
Better torrent name when dropping a folder

### ISSUE THREAD

**Issue by feross** [feross/instant.io#49]
When dropping multiple files, or a folder (which will soon be supported for Chrome!), we currently just pick the first file name as the name of the torrent. This is confusing. What should we name the torrent instead?

**Comment by jakefb** [comment]
The best option I can think of is asking the user what they want to name the torrent? Or we could name it something like like "file1,file2.torrent" or "2files.torrent" but that's a bit silly.

**Comment by feross** [comment]
closing because i dont think is an important problem
