### ISSUE TITLE
Downloading from .torrent files is broken

### ISSUE THREAD

**Issue by gmbuell** [feross/instant.io#50]
instant.io gives "Uncaught Error: Invalid torrent identifier" in the javascript console when trying to download from a torrent file rather than info hash or magnet link.

Steps to reproduce:

1. Start seeding a file on instant.io
2. Download the torrent for the file
3. Open the torrent in a new tab at instant.io

I'm using Chrome Version 43.0.2357.81

**Comment by feross** [comment]
Sorry, I broke this feature when I switched `drag-drop` to use file blobs instead of Buffer, so we could use less RAM. Just fixed it.

Please try it out on https://instant.io and let me know if you see other issues.

**Comment by feross** [comment]
Okay, this code is now deployed to https://instant.io.
