### ISSUE TITLE
Only works with websocket trackers

### ISSUE THREAD

**Issue by gmbuell** [feross/instant.io#52]
Setting TRACKER_URL to an http or udp tracker does not work (and does not produce any errors).

**Comment by feross** [comment]
Yeah, this is a limitation of the browser. The browser can't make TCP or UDP connections for security reasons. No browsers can do this.

**Comment by gmbuell** [comment]
UDP totally makes sense but why can't the browser query the http interface?



—

**Comment by feross** [comment]
Assuming the http tracker set the correct cross-origin headers (unlikely), what would the browser do with the resulting ip:port addresses that the tracker returns? It can't make TCP connections, so it's not very useful.

The browser can only make webrtc connections.

**Comment by gmbuell** [comment]
Oh I certainly agree the connections to peers would have to be websocket. I'm unfamiliar with the details of WebTorrent. Are the peers returned by the websocket tracker in a different format than the http version to distinguish them as websocket? The idea here is that websocket clients could still use something like opentracker rather than being restricted to bittorrent-tracker (not that there's anything wrong with it, just for ease of setup).



—

**Comment by feross** [comment]
Sorry that this isn't clearer from the documentation. I'm working on improving docs. Right now, webtorrent in the browser MUST use a websocket tracker. The only implementation of a websocket tracker is currently the `bittorrent-tracker` package. Maybe opentracker could support websockets in the future? But until then, you have to use `bittorrent-tracker`.

The peers returned from the websocket tracker are fundamentally different than those for normal bittorrent. Normal bittorrent returns "ip:port" addresses. The websocket tracker returns webrtc offer/answers. It's a bit more complicated :)

**Comment by gmbuell** [comment]
Ahh I see thanks for clearing that up. Is there a more formal spec for the websocket tracker RPC? Or is it just the code right now?



—

**Comment by feross** [comment]
Right now it's just the code, but it's quite simple. It's very similar to the current tracker spec, but with a few changes to accommodate webrtc. I'll write up a formal spec asap.
