### ISSUE TITLE
Is instant.io and its tracker down right now?

### ISSUE THREAD

**Issue by jakefb** [feross/instant.io#54]
I checked a few hours ago and https://instant.io/ seemed to be down. It still is and I was wondering what's happening? I was thinking about running my own tracker, but if I did would peers from my website using my tracker, be able to connect to peers from instant.io?

**Comment by feross** [comment]
Yes, https://instant.io and the webtorrent tracker are both down at the moment because the Linode Fremont data center is experiencing an outage.

I posted about here: https://twitter.com/feross/status/604476316226699264
You can follow updates here: http://status.linode.com/

**Comment by feross** [comment]
Please run your own tracker! You can use it in addition to tracker.webtorrent.io and it will work just fine. If tracker.webtorrent.io is down, you would still be able to connect to peers on the other tracker.

If you share the URL with me, I will add it to https://instant.io so we can have redundancy. The package is `bittorrent-tracker`, and you can see an example of how it's used at the `feross/webtorrent-website` repo.

**Comment by feross** [comment]
If you switched to ONLY using your own tracker and removed tracker.webtorrent.io your users wouldn't be able to connect to anyone else using tracker.webtorrent.io (like instant.io and most other users of webtorrent right now). So, add it to the list of trackers, but don't remove tracker.webtorrent.io.

**Comment by jakefb** [comment]
Thanks for the information. If most people are using tracker.webtorrent.io for their projects as well as when using instant.io, does the tracker handle all the connections well? Having more than one tracker would definitely make the network more redundant. I will try set up my own tracker soon and let you know!

**Comment by feross** [comment]
So far the tracker hasn't had any issues scaling. We'll probably run into issues scaling the tracker software at some point, but we can fix those as they arise.

Thanks - let me know if you have difficulties setting up the tracker so I can make the process easier. If you want, take note of what you do to get the tracker up and we can add those instructions as documentation!

**Comment by rom1504** [comment]
I set up a tracker on "ws://tracker.rom1504.fr" (and an instant.io mirror that use both tracker on http://instant.rom1504.fr)

Example : http://instant.rom1504.fr/#1a7b7e6b2dbdac534aa1cd543d9ec41541ab56f0 (also works on https://instant.io/#1a7b7e6b2dbdac534aa1cd543d9ec41541ab56f0)

**Comment by jakefb** [comment]
Nice work rom1504. I have deployed a tracker at ws://tracker.fastcast.nz. I made a minimal version of ``feross/webtorrent-website`` which just has the code for the tracker. This can be found in the repo I made ``jakefb/fastcast-tracker``. People who want to set up their own tracker could just clone the repository and change the IP address on the second line of config.js from ``'144.6.227.30'`` to ``'localhost'``, or something along those lines.

Here's how I set up the tracker on my server:

    git clone https://github.com/jakefb/fastcast-tracker.git
    cd fastcast-tracker
    npm install
    npm install forever -g
    forever start -l forever.log -o out.log -e err.log server/tracker.js

My nginx config:

    server {
      listen 80;

      server_name tracker.fastcast.nz;

      location / {
        proxy_pass http://localhost:9003;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
      }
    }

Change the server_name to the name of the subdomain you wish to use. You can also change http://localhost:9003 to the IP of a different host. Last, create an A record in your DNS which points the subdomain at the IP of your web server.

An example of using my tracker in use: 

You can seed a video from http://fastcast.nz/seed.html and it should appear on http://fastcast.nz/videos/agitation-new-zealand-4k.html. You can also see the video load on https://instant.io/#62311eba4e957a86d92a9152cbe87417e07632dd.

**Comment by feross** [comment]
The main tracker has been back up for a while. :+1: Closing this issue now.

Thanks for setting up mirrors @rom1504 and @jakefb! Let me know when you guys get SSL (wss://) working and I'll add your mirrors to instant.io. SSL really improves the probably that websockets will work. Proxies and ISPs often mess up ws:// connections.

**Comment by jakefb** [comment]
Do I need to buy a signed certificate to setup SSL? If so could you reccomend a cost effective solution?

**Comment by feross** [comment]
Namecheap sells SSL certs for $9/yr. https://www.namecheap.com/security/ssl-certificates/domain-validation.aspx I use the multi-domain version on webtorrent.io, since I wanted to cover webtorrent.io and tracker.webtorrent.io.

It's just $2 for first year if you buy a domain or renew something with them. https://www.namecheap.com/promos/exclusive-positive-ssl-offer.aspx

https://www.startssl.com/ claims to offer free certs. Haven't tried it myself.

https://letsencrypt.org/ plans to offer free certs soon (mid 2015) and it's run by Mozilla and the EFF.
