### ISSUE TITLE
Video autoplay

### ISSUE THREAD

**Issue by Pawtiko** [feross/instant.io#61]
The video previews autoplay when you upload them, but if you upload more than one video at once, they all play at the same time.

**Comment by feross** [comment]
PR welcome!

**Comment by Pawtiko** [comment]
I'm sorry, but I don't understand what PR means in this context. Could you tell me what that means?

**Comment by rom1504** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by nevilgeorge** [comment]
Should the expected behavior be to play only the first video?

**Comment by feross** [comment]
Yeah, I think that's right.
