### ISSUE TITLE
Large files fail to load

### ISSUE THREAD

**Issue by Pawtiko** [feross/instant.io#62]
Uploading large files (I tested with a file 1.25 GB large) fails to start seeding
![screencapture-instant-io-1433813314604](https://cloud.githubusercontent.com/assets/7896913/8048952/1e877d26-0e26-11e5-9a0f-1dc96f6dfb07.png)
.

**Comment by feross** [comment]
The node.js buffer has a max limit of 1GB right now. Until we switch away from the in-memory representation of the torrent, we're stuck with this.

More info: https://github.com/feross/webtorrent/issues/319
