### ISSUE TITLE
For media source file types, use a waterfall of fallbacks

### ISSUE THREAD

**Issue by feross** [feross/instant.io#66]
Right now, the way we handle fallback is inconsistent. Here's what I think we should do:

1. If `videostream` supports the file type, try to use it.
2. If video/audio tag emits 'error', try using MediaSource directly
3. If video/audio tag emits another 'error' (and file is < 1GB), use blob url approach (this requires full file download, i.e. it's not streaming)

Pull out this logic into it's own function and re-use it for video and audio.

cc @jhiesey - thoughts?

**Comment by jhiesey** [comment]
That sounds reasonable to me.
