### ISSUE TITLE
npm install fails to install posix

### ISSUE THREAD

**Issue by zyzof** [feross/instant.io#69]
I am trying to set up a server in a Windows environment (though I've tried on Ubuntu 14.04, similarly fails on posix install). Here is the error:

 posix.cc
..\src\posix.cc(2): fatal error C1083: Cannot open include file: 'unistd.h': No
 such file or directory [<projdir>\instant.io\node_modul
es\posix\build\posix.vcxproj]

...

npm ERR! posix@2.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the posix@2.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the posix package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls posix
npm ERR! There is likely additional logging output above.

Any idea what's going on here? I'm fairly new to node and npm and not sure where to go from here. 

Is it in fact a problem with posix? The only somewhat useful looking thing I've found on StackOverflow is http://stackoverflow.com/a/27709968/1388195, but not sure where I'd find the io.h replacement for unistd.h mentioned.

Really looking forward to playing around with this and WebTorrent, and appreciate any help :)

Cheers,
Simon

**Comment by zyzof** [comment]
I've managed to get things up and running on Ubuntu, so I guess I'll just stick with that. Turned out the Ubuntu posix install error was due to the node binary being used actually being the "Amateur Packet Radio Node Program". See [this StackOverflow answer](http://stackoverflow.com/a/18130296/1388195).

**Comment by feross** [comment]
Oh, yes. On ubuntu, you can solve this by running: `sudo apt-get install nodejs-legacy` which gives you a `node` symlink.

I think we should still fix the issue on Windows.

**Comment by feross** [comment]
The issue with the `posix` package should be fixed on Windows now. Let me know if you have further issues.

I published [downgrade](https://github.com/feross/downgrade) and [unlimited](https://github.com/feross/unlimited) that work on windows and made instant.io use those packages.

**Comment by zyzof** [comment]
unlimited appears to have the same error, failing on posix.

Running `node server/index.js gives the following:

E:\Devel\Torrents\instant.io\node_modules\downgrade\index.js:17
      process.getuid(), uid, process.getgid(), gid
              ^
TypeError: undefined is not a function
    at downgrade (E:\Devel\Torrents\instant.io\node_modules\downg
rade\index.js:17:15)
    at E:\Devel\Torrents\instant.io\server\index.js:168:3
    at zalgoSafe (E:\Devel\Torrents\instant.io\node_modules\run-p
arallel\node_modules\dezalgo\dezalgo.js:20:10)
    at done (E:\Devel\Torrents\instant.io\node_modules\run-parall
el\index.js:18:15)
    at Server.g (events.js:199:16)
    at Server.emit (events.js:104:17)
    at net.js:1171:12
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)

**Comment by feross** [comment]
@zyzof Sorry about that. Can you delete your `node_modules` folder, re-install, and try again? I didn't know that node.js's `process.getuid` is undefined on windows. This is fixed now.
