### ISSUE TITLE
add magnet: protocol handler

### ISSUE THREAD

**Issue by feross** [feross/instant.io#74]
We can actually intercept clicks on `magnet:` links and direct them to https://instant.io!

https://developer.mozilla.org/en-US/docs/Web-based_protocol_handlers

Why didn't I think of this before?

**Comment by feross** [comment]
This is live on instant.io now!

**Comment by rom1504** [comment]
Does that mean that clicking on the "[Magnet URI]" link on instant.io should start a new tab with instant.io downloading that magnet ?
Doesn't seem to work here (chrome 43)

**Comment by feross** [comment]
@rom1504 You have to click the little icon on the address bar to enable it:

![screen shot 2015-07-29 at 2 34 56 am](https://cloud.githubusercontent.com/assets/121766/8954441/7c8527fc-359a-11e5-9f05-617ac3d97c22.png)

In Firefox, you click the "+" icon in the search bar:

![screen shot 2015-07-28 at 5 58 07 pm](https://cloud.githubusercontent.com/assets/121766/8954451/881bb20c-359a-11e5-847f-713db42e9236.png)

**Comment by rom1504** [comment]
Yeah I just saw that !
In firefox it actually also ask it with a small banner under the address bar.

**Comment by feross** [comment]
Right!
