### ISSUE TITLE
Error uploading large files

### ISSUE THREAD

**Issue by marianobrc** [feross/instant.io#79]
I've tried to upload a video MP4 file to instant.io to seed it and i got this error on the console:

Uncaught RangeError: Invalid typed array lengthallocate 
@ bundle.js:566fromNumber 
@ bundle.js:469Buffer 
@ bundle.js:456Storage 
@ bundle.js:10817Torrent._onMetadata 
@ bundle.js:11404Torrent._onSwarmListening 
@ bundle.js:11361(anonymous function) 
@ bundle.js:8511RawTask.call @ bundle.js:8566flush @ bundle.js:8639

The file size is 1.9 GB. Then never appears the infohash, neither links to URL / magnet lint / .torrent.

**Comment by feross** [comment]
How big is the file?

**Comment by marianobrc** [comment]
The file size is 1.9 GB. I've tried with another smaller video of 8MB and it works just fine.

**Comment by feross** [comment]
@marianobrc The max file size that is supported is dependent on your processor architecture. 32-bit browsers have 1GB max. 64-bit browsers *should* support up to 2GB.
