### ISSUE TITLE
Doesn't work for me as a download client

### ISSUE THREAD

**Issue by Drugoy** [feross/instant.io#93]
I once visited instant.io and browser (latest Firefox release, x32) asked whether I want to add this site as a handler for ``magnet:`` URIs and I agreed.
Now I visit some piratebay trackers and click on a magnet link - I get redirected to an instant.io  page where all I see is
```
Log

Downloading torrent from magnet:?xt=urn:btih:9983a9942b9ff9c1d4b9ce2ec6bbb135f0d707df&dn=Family.Guy.S14E08.720p.HDTV.x264-KILLERS%5Bettv%5D&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969
```

and nothing ever happens.
W7SP1x64

**Comment by Drugoy** [comment]
Java Error Console Log:
```
The connection to wss://tracker.btorrent.xyz/ was interrupted while the page was loading. bundle.js:17237:0 view-source:https://instant.io/bundle.js
The connection to wss://tracker.webtorrent.io/ was interrupted while the page was loading. bundle.js:17237:0 view-source:https://instant.io/bundle.js
GET https://instant.io/#magnet%3A%2Fxt=urn:btih:9983a9942b9ff9c1d4b9ce2ec6bbb135f0d707df&dn=Family.Guy.S14E08.720p.HDTV.x264-KILLERS%5Bettv%5D&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969 [HTTP/1.1 200 OK 917ms]
GET https://instant.io/main.css [HTTP/1.1 200 OK 556ms]
GET https://instant.io/bundle.js [HTTP/1.1 200 OK 922ms]
about:blank : Unable to run script because scripts are blocked internally. <unknown>
TypeError: asm.js type error: Disabled by debugger bundle.js
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create bundle.js:3203:3 view-source:https://instant.io/bundle.js
GET XHR https://instant.io/rtcConfig [HTTP/1.1 200 OK 182ms]
GET https://instant.io/favicon.ico [HTTP/1.1 304 Not Modified 183ms]
GET https://tracker.btorrent.xyz/ [HTTP/1.1 101 Switching Protocols 390ms]
GET https://tracker.webtorrent.io/ [HTTP/1.1 101 Switching Protocols 556ms]
GET https://instant.io/favicon.ico [HTTP/1.1 304 Not Modified 182ms]
ICE failed, see about:webrtc for more details
```

**Comment by rom1504** [comment]
@Drugoy most torrents aren't seeded in the webrtc networks.

**Comment by Drugoy** [comment]
@rom1504 could you elaborate please? Did I get you right that instant.io if used as a torrent client (for leeching) can only leech from peers that also use instant.io (for seeding)?
I thought instant.io can replace a torrent client, and you say that it's actually an extra to it?
Are there any modern desktop torrent clients that can also work via webrtc networks?

Someone, please, add some FAQ for less tech-savvy people that stumble upon this project.

**Comment by rom1504** [comment]
![image](https://raw.githubusercontent.com/feross/webtorrent/master/img/network.png)

and more generally see https://github.com/feross/webtorrent

browsers cannot use TCP, so they cannot connect to normal clients

**Comment by DiegoRBaquero** [comment]
Instant.io can only connect to webrtc peers. You could use webtorrent in node for what you are looking for :)

**Comment by Drugoy** [comment]
From webtorrent's info:
> To seed files to web peers, use a client that supports WebTorrent, e.g. webtorrent-hybrid or instant.io.

I thought this means that instant.io is a webtorrent-hybrid that would let me download files from bittorent trackers.

I am now confused: what's the difference between instant.io and webtorrent.io?

> **WebTorrent** is a streaming torrent client for **node.js** and the **browser**.

So if webtorrent.io is a torrent client then instant.io must be the hybrid node.
Am I wrong?

**Comment by DiegoRBaquero** [comment]
No no no, you are confusing things. WebTorrent.io is just a website that uses WebTorrent (in its main page for the video)

Instant.io is a WebTorrent client for webrtc peers only.

No WebTorrent client in the browser can connect to TCP/uTP nataurally, unless extesion were added or something.

webtorrent-hybrid is a node module that you can install. Check https://github.com/feross/webtorrent-hybrid

**Comment by Drugoy** [comment]
So WebTorrent (bittorrents + werbrtc-torrents) > instant.io (only webrtc-torrents), but WebTorrent requires node.js stuff, while instant.io requires just a modern browser.
Got it, thanks! :)

**Comment by DiegoRBaquero** [comment]
@Drugoy WebTorrent is for bittorrent in node, webrtc-torrents in browser. WebTorrent-Hybrid is for both types in node.

Instant.io is just a website that **uses** WebTorrent, so webrtc-torrents only.
βTorrent.xyz is a website browser-client that **uses** WebTorrent, so webrtc-torrents only.

**Comment by Zibri** [comment]
why is I go to instant.io I read this in the console?

WebSocket connection to 'wss://tracker.fastcast.nz/' failed: Error in connection establishment: net::ERR_BLOCKED_BY_CLIENT
WrappedWebSocket @ VM46:164
VM46:164 WebSocket connection to 'wss://tracker.openwebtorrent.com/' failed: Error in connection establishment: net::ERR_BLOCKED_BY_CLIENT
WrappedWebSocket @ VM46:164
VM46:164 WebSocket connection to 'wss://tracker.btorrent.xyz/' failed: Error in connection establishment: net::ERR_BLOCKED_BY_CLIENT
WrappedWebSocket @ VM46:164
VM46:164 WebSocket connection to 'wss://tracker.openwebtorrent.com/' failed: Error in connection establishment: net::ERR_BLOCKED_BY_CLIENT
WrappedWebSocket @ VM46:164
Socket @ bundle.js:20142
WebSocketTracker._openSocket @ bundle.js:2492
(anonymous) @ bundle.js:2662
VM46:164 WebSocket connection to 'wss://tracker.fastcast.nz/' failed: Error in connection establishment: net::ERR_BLOCKED_BY_CLIENT

**Comment by feross** [comment]
@Zibri That can happen if your ad blocker is blocking connections to the WebTorrent trackers. Try disabling your ad blocker. Also see: https://github.com/webtorrent/webtorrent/issues/1292
