### ISSUE TITLE
Streaming File

### ISSUE THREAD

**Issue by oknoorap** [feross/instant.io#97]
Can I download file like pdf, mp3, etc? I tried to paste magnet link (e.g pdf format) but doesn't work.
e.g URL https://kat.cr/books/
thanks..

**Comment by alxhotel** [comment]
Please read [issue #466](https://github.com/feross/webtorrent/issues/466)

**Comment by oknoorap** [comment]
Thanks. Okay I see, so webtorrent doesn't support external peers, i thought webtorrent adopts the philosophy of "torrent" but it actually a web peers not "torrent" because only support internal peers.

**Comment by rom1504** [comment]
not internal peers, webrtc peers.

**Comment by oknoorap** [comment]
@rom1504 okay :smile:  :+1: apologize noob here

**Comment by feross** [comment]
@oknoorap Please don't discuss copyright infringement on the issue tracker. That is not allowed and we cannot help with those types of requests.
