### ISSUE TITLE
Avi doesn't append to DOM

### ISSUE THREAD

**Issue by Saheb** [feross/instant.io#98]
![image](https://cloud.githubusercontent.com/assets/1163256/12398456/d5b3156e-be39-11e5-8dbf-ae4e042d10a8.png)

**Comment by feross** [comment]
AVI is not supported for streaming by WebTorrent. It's actually surprisingly difficult to support new video formats, as @jhiesey will attest :) If you'd like to help add support for more formats, check out [videostream](https://npmjs.com/package/videostream) where most of this work is happening.
