### ISSUE TITLE
can't get main.css & bundle.js when running this site on my own server

### ISSUE THREAD

**Issue by charon4ever** [feross/instant.io#99]

**Comment by joshterrill** [comment]
In order for the `main.css` and `bundle.js` files to be created, you have to run the npm build command that is defined in `package.json`. Running this compiles the css and js files needed to run the app.

**Comment by feross** [comment]
Yep, @joshterrill is correct!

**Comment by nodiscc** [comment]
Is a prebuilt version available somewhere? I think [attaching](https://github.com/blog/1547-release-your-software) a prebuilt, ready-to-unzip-and-use archive to the next release would be great. Thanks for your work on this really nice project.

**Comment by feross** [comment]
Is running:

```
npm install
npm build
npm start
```

too hard?

I'm kind of hesitant to pre-bundle the assets because it makes pushing code to the repo a bit harder – adds an extra step for me every time.

**Comment by joshterrill** [comment]
@feross you can actually do it with just the install and start, build is included in the start script.

**Comment by feross** [comment]
@joshterrill Nice, I forgot about that :)

```
npm install
npm start
```
